selenium-hub:
  image: selenium/hub
  ports:
    - "4444:4444"
  volumes:
      - /dev/shm:/dev/shm
  privileged: true

chrome:
    image: selenium/node-chrome
    links:
      - selenium-hub:hub
    volumes:
      - /dev/shm:/dev/shm
    privileged: true